apiVersion: activemonitor.keikoproj.io/v1alpha1
kind: HealthCheckJob
metadata:
  generateName: dns-healthcheck-
  namespace: health
spec:
  repeatAfterSec: 60
  description: "Monitor pod dns connections"
  job:
    generateName: dns-workflow-
    timeout: 60
    resource:
      namespace: health
      serviceAccount: activemonitor-controller-sa
      schedule: "* * * * *"
      activeDeadlineSeconds: 65
      ttlSecondsAfterFinished: 180
      labels:
        jobs.keikoproj.io/controller-instanceid: active-monitor-job
      template:
        spec:
          containers:
            - name: start
              image: docker.intuit.com/personal/sagarwal23/tutum/dnsutils
              command: [ sh, -c ]
              args: [ "nslookup www.google.com" ]
          tolerations:
            - effect: NoExecute
              operator: Exists
            - effect: NoSchedule
              operator: Exists
          restartPolicy: Never
